[package]
name = "dbl-rs"
version = "0.1.0"
description = "API Bindings for discordbots.org"
readme = "README.md"
repository = "https://github.com/nickelc/dbl-rs"
license = "MIT/Apache-2.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]
keywords = ["discord", "bots"]
categories = ["api-bindings", "web-programming::http-client"]
edition = "2018"

[lib]
name = "dbl"

[dependencies]
futures = "0.1"
reqwest = "0.9"
serde_json = "1"

[dependencies.serde]
version = "1"
features = ["derive"]
