name: ci

on: [push, pull_request]

jobs:
  lints:
    name: Format and clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install rust (stable)
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy, rustfmt

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

      - name: Run rustfmt
        run: cargo fmt --all -- --check

  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, beta, nightly]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install rust (${{ matrix.rust }})
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - name: Check default features
        run: cargo check --examples --tests

      - name: Tests
        run: cargo test --all-features

      - name: Check webhook example
        run: cargo check --manifest-path examples/webhook/Cargo.toml
